### ISSUE TITLE
文件夹名字里有小数点时，提示不是文件夹

### ISSUE THREAD

**Issue by woodycarl** [piratf/windows-folder-remark#1]
如题

**Comment by piratf** [comment]
您好，很抱歉过了十天才进行回复，我在我的 Win10 平台上进行了测试没有重现这个 bug

![image](https://cloud.githubusercontent.com/assets/9389616/15271954/9558c93e-1a94-11e6-8eef-8de98dbd2c24.png)

您可以告知我您的使用平台，以及使用此工具的方式吗？这会便于我重现并定位 bug，谢谢你。

**Comment by woodycarl** [comment]
哦，整错了，我还以为是拖进去后，加空格和备注内容呢。。使用方法不当，抱歉

2016-05-15 12:01 GMT+08:00 潘 notifications@github.com:

> 您好，很抱歉过了十天才进行回复，我在我的 Win10 平台上进行了测试没有重现这个 bug
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/9389616/15271954/9558c93e-1a94-11e6-8eef-8de98dbd2c24.png
> 
> 您可以告知我您的使用平台，以及使用此工具的方式吗？这会便于我重现并定位 bug，谢谢你。
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/piratf/windows-folder-remark/issues/1#issuecomment-219265045

## 

_woodycarl http://blog.woodycarl.me_
