### ISSUE TITLE
建议将功能集成到右键菜单

### ISSUE THREAD

**Issue by DCGZH** [piratf/windows-folder-remark#2]
建议在文件夹右键菜单里增加一项【Folder Remark】
选中后直接弹出一个窗口，输入要备注的内容就可以。
// 也可以直接弹出一个DOS窗口，然后自动获取文件夹路径，只需要自己输入备注，这样应该改动是最小的

**Comment by piratf** [comment]
我 pin 一下这个 issue，欢迎感兴趣的朋友尝试。

**Comment by everXXfor** [comment]
我对这个项目修改了一下集成到右键菜单了
仓库地址  https://github.com/ChunkHsu/windows-folder-remark
效果如下：
![image](https://github.com/piratf/windows-folder-remark/assets/103046033/661ba97e-733a-4bc4-9f5c-13e01ceef72b)

**Comment by piratf** [comment]
加了右键菜单功能 #11 
https://github.com/piratf/windows-folder-remark/releases
