### ISSUE TITLE
日文路径的文件无法备注

### ISSUE THREAD

**Issue by worldYang** [piratf/windows-folder-remark#3]
日文路径的文件不知道是不是太长了还是日文的原因，显示不是有效的路径。改了名字后可以备注了

**Comment by worldYang** [comment]
> 日文路径的文件不知道是不是太长了还是日文的原因，显示不是有效的路径。改了名字后可以备注了

好吧，是有空格不能备注，没空格就可以了

**Comment by piratf** [comment]
已发布修复，感谢你的反馈
