### ISSUE TITLE
添加备注后文件夹变成了系统文件夹 

### ISSUE THREAD

**Issue by jieYM** [piratf/windows-folder-remark#4]
添加备注后文件夹变成了系统文件夹，后面我是通过 cmd下"attrib -h -r -a -s 目标文件夹名"的方式修正的

**Comment by piratf** [comment]
https://answers.microsoft.com/en-us/windows/forum/all/how-do-i-add-comments-to-a-folder-within-file/7f5e1825-47ec-4276-bce9-0cfd4c66e5f5?auth=1

文件夹注释的原理是系统处理 desktop.ini 配置并加以展示，因此为文件夹设置系统属性是必要的。
如果有不用设置系统属性的方式欢迎分享~

我更新了 Readme，让这部分的说明更加明显了。
