### ISSUE TITLE
解决了无法向『含空格的文件夹』添加备注的问题

### ISSUE THREAD

**Issue by kusunoki-riko** [piratf/windows-folder-remark#5]
runCommand('attrib \"' + settingFilePath + '\" -s -h')

**Comment by kusunoki-riko** [comment]
其实就是在三处runCommand函数里面，把传入的文件路径用引号包裹起来就好了。

**Comment by kusunoki-riko** [comment]
可以的话，更新下代码吧 @piratf

**Comment by NGdapang** [comment]
大佬，这个修改源码要修改哪个文件？😱用什么编译器打开?想根据你的办法把这个问题修复下(自用)......😳

**Comment by piratf** [comment]
已经发布修复，感谢二位的支持。
